on: [push, workflow_dispatch]
    
name: Find LaunchDarkly flag code references
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Check out repo to scan
      uses: actions/checkout@v3
      with:
        path: repo-to-scan
        repository: launchdarkly/SupportService
        fetch-depth: 11
    - name: LaunchDarkly Code References
      uses: ./
      with:
        accessToken: ${{ secrets.LD_ACCESS_TOKEN }}
        debug: true
        ignoreServiceErrors: true
        projKey: support-service
        allowTags: true
      env:
        LD_DIR: ${{ github.workspace }}/repo-to-scan
