on: [push, workflow_dispatch]
    
name: Test multiple repo checkout 

jobs:
  find-code-references:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 10
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        path: repo-to-scan
        repository: launchdarkly/SupportService
        fetch-depth: 10
        ref: 99fef7e # test
    - name: LaunchDarkly Code References
      uses: launchdarkly/find-code-references@master
      with:
        accessToken: ${{ secrets.LD_ACCESS_TOKEN }}
        debug: true
        ignoreServiceErrors: true
        projKey: support-service
        allowTags: true
        repoName: SupportService-2
      env:
        LD_DIR: ${{ github.workspace }}/repo-to-scan
